---
document:
  name: Regole tecniche
  description: |
    SPID, il Sistema Pubblico di Identità Digitale, è la soluzione che ti
    permette di accedere a tutti i servizi online della Pubblica
    Amministrazione con un’unica Identità Digitale (username e password)
    utilizzabile da computer, tablet e smartphone.
  tags:
    - "spid"
